### ISSUE TITLE
With multi-process option, plugin's widget often not shown max size

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#44] opened 2012-12-07 01:02 UTC
```
% rosrun rqt_gui rqt_gui -m
```

Seen with rqt_pr2_dashboard, rqt_console, rqt_bag, rqt_logger_level so far. This happens almost always, but sometimes the plugin max sized.

Once I resize rqt_gui's window, the plugin adjusts the size to expand to the maximum available size within the window.

Groovy
qt_gui_core from debian
rqt from src

**Comment by ablasdel** [comment] 2012-12-07 04:51
You should put the specific version of the qt_gui_core and the specific commit from source. 
That way if this one is open for awhile we know where to test if it is not reproduce-able.

If this happens with all plugins this might be a qt_gui_core level bug

**Comment by 130s** [comment] 2012-12-07 07:07
Good point.
ros-groovy-qt-gui-core/precise uptodate 0.2.7-0precise-20121205-0847-+0000
rqt f3cfe76373cb30b540d444f792ad3cc7f6f32777

**Comment by 130s** [comment] 2012-12-07 19:47
Just pasting a commandline output sample. 

What I did is in order:
1. ran rqt_gui in multiprocess mode
2. open & close rqt_bag
3. open & close rqt_console
4. close rqt_gui

```
(gdb) run bin/rqt_gui -m
Starting program: /usr/bin/python bin/rqt_gui -m
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdb114700 (LWP 21481)]
[New Thread 0x7fffda913700 (LWP 21482)]
WARNING(s) in /opt/ros/groovy/share/pcl/package.xml:
- The manifest must not contain the following tags: copyright
WARNING(s) in /opt/ros/groovy/share/convex_decomposition/package.xml:
- The manifest must not contain the following tags: copyright
- The "description" tag must not have the following attributes: brief
WARNING(s) in /opt/ros/groovy/share/flann/package.xml:
- The manifest must not contain the following tags: run-depend
WARNING(s) in /opt/ros/groovy/share/image_geometry/package.xml:
- The manifest must not contain the following tags: copyright
WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
WARNING(s) in /opt/ros/groovy/share/cv_bridge/package.xml:
- The manifest must not contain the following tags: copyright
RosPluginlibPluginProvider::load_explicit_type(rqt_gui_cpp/RosCppPluginProvider) could not load library (Could not find library.)
RecursivePluginProvider.discover() loading plugin 'rqt_gui_cpp/RosCppPluginProvider' failed
WARNING(s) in /opt/ros/groovy/share/pcl/package.xml:
- The manifest must not contain the following tags: copyright
WARNING(s) in /opt/ros/groovy/share/convex_decomposition/package.xml:
- The manifest must not contain the following tags: copyright
- The "description" tag must not have the following attributes: brief
WARNING(s) in /opt/ros/groovy/share/flann/package.xml:
- The manifest must not contain the following tags: run-depend
WARNING(s) in /opt/ros/groovy/share/image_geometry/package.xml:
- The manifest must not contain the following tags: copyright
WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
WARNING(s) in /opt/ros/groovy/share/cv_bridge/package.xml:
- The manifest must not contain the following tags: copyright
[New Thread 0x7fffc7dcc700 (LWP 21509)]
    21510 WARNING(s) in /opt/ros/groovy/share/pcl/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 WARNING(s) in /opt/ros/groovy/share/convex_decomposition/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 - The "description" tag must not have the following attributes: brief
    21510 WARNING(s) in /opt/ros/groovy/share/flann/package.xml:
    21510 - The manifest must not contain the following tags: run-depend
    21510 WARNING(s) in /opt/ros/groovy/share/image_geometry/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
    21510 WARNING(s) in /opt/ros/groovy/share/cv_bridge/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 RosPluginlibPluginProvider::load_explicit_type(rqt_gui_cpp/RosCppPluginProvider) could not load library (Could not find library.)
    21510 RecursivePluginProvider.discover() loading plugin 'rqt_gui_cpp/RosCppPluginProvider' failed
    21510 WARNING(s) in /opt/ros/groovy/share/pcl/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 WARNING(s) in /opt/ros/groovy/share/convex_decomposition/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 - The "description" tag must not have the following attributes: brief
    21510 WARNING(s) in /opt/ros/groovy/share/flann/package.xml:
    21510 - The manifest must not contain the following tags: run-depend
    21510 WARNING(s) in /opt/ros/groovy/share/image_geometry/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21510 WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
    21510 WARNING(s) in /opt/ros/groovy/share/cv_bridge/package.xml:
    21510 - The manifest must not contain the following tags: copyright
    21544 WARNING(s) in /opt/ros/groovy/share/pcl/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 WARNING(s) in /opt/ros/groovy/share/convex_decomposition/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 - The "description" tag must not have the following attributes: brief
    21544 WARNING(s) in /opt/ros/groovy/share/flann/package.xml:
    21544 - The manifest must not contain the following tags: run-depend
    21544 WARNING(s) in /opt/ros/groovy/share/image_geometry/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
    21544 WARNING(s) in /opt/ros/groovy/share/cv_bridge/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 RosPluginlibPluginProvider::load_explicit_type(rqt_gui_cpp/RosCppPluginProvider) could not load library (Could not find library.)
    21544 RecursivePluginProvider.discover() loading plugin 'rqt_gui_cpp/RosCppPluginProvider' failed
    21544 WARNING(s) in /opt/ros/groovy/share/pcl/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 WARNING(s) in /opt/ros/groovy/share/convex_decomposition/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 - The "description" tag must not have the following attributes: brief
    21544 WARNING(s) in /opt/ros/groovy/share/flann/package.xml:
    21544 - The manifest must not contain the following tags: run-depend
    21544 WARNING(s) in /opt/ros/groovy/share/image_geometry/package.xml:
    21544 - The manifest must not contain the following tags: copyright
    21544 WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
    21544 WARNING(s) in /opt/ros/groovy/share/cv_bridge/package.xml:
    21544 - The manifest must not contain the following tags: copyright
[ERROR] [WallTime: 1354909538.461233] Unable to append (PyQt4.QtCore.QByteArray('\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x01\xf4\x00\x00\x01\xf4\x01\x00\x00\x00\t\x01\x00\x00\x00\x02'),) to message with signature v: <type 'exceptions.TypeError'>: Don't know which D-Bus type to use to encode type "QByteArray"
    21544 PluginHandlerDirect._restore_settings() plugin "rqt_console/Console#1" raised an exception:
    21544 Traceback (most recent call last):
    21544   File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 116, in _restore_settings
    21544     self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
    21544   File "/u/isaito/link/groovy_catkinws/rqt/rqt_console/src/rqt_console/console.py", line 105, in restore_settings
    21544     self._mainwindow.restore_settings(plugin_settings, instance_settings)
    21544   File "/u/isaito/link/groovy_catkinws/rqt/rqt_console/src/rqt_console/console_widget.py", line 582, in restore_settings
    21544     self.table_splitter.restoreState(instance_settings.value('table_splitter'))
    21544   File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/settings.py", line 88, in value
    21544     value = self._settings_proxy.value(self._group, key, default_value)
    21544   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    21544     **keywords)
    21544   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    21544     message, timeout)
    21544 DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
    21544   File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    21544     _method_reply_return(connection, message, method_name, signature, *retval)
    21544   File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    21544     reply.append(signature=signature, *retval)
    21544 TypeError: Don't know which D-Bus type to use to encode type "QByteArray"
    21544 
    21544 
    21544 PluginHandlerDirect._save_settings() plugin "rqt_console/Console#1" raised an exception:
    21544 Traceback (most recent call last):
    21544   File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 106, in _save_settings
    21544     self._plugin.save_settings(plugin_settings_plugin, instance_settings_plugin)
    21544   File "/u/isaito/link/groovy_catkinws/rqt/rqt_console/src/rqt_console/console.py", line 102, in save_settings
    21544     self._mainwindow.save_settings(plugin_settings, instance_settings)
    21544   File "/u/isaito/link/groovy_catkinws/rqt/rqt_console/src/rqt_console/console_widget.py", line 560, in save_settings
    21544     instance_settings.set_value('table_splitter', self.table_splitter.saveState())
    21544   File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/settings.py", line 81, in set_value
    21544     self._settings_proxy.set_value(self._group, key, value)
    21544   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    21544     **keywords)
    21544   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    21544     message.append(signature=signature, *args)
    21544 TypeError: Don't know which D-Bus type to use to encode type "QByteArray"
    21544 
[Thread 0x7fffc7dcc700 (LWP 21509) exited]
[Thread 0x7fffdb114700 (LWP 21481) exited]
[Thread 0x7ffff7fca700 (LWP 21480) exited]
[Inferior 1 (process 21480) exited normally]
```

**Comment by dirk-thomas** [comment] 2020-06-12 17:39
Closing since this option doesn't exist for quite a while: see https://github.com/ros-visualization/rqt/issues/127#issuecomment-378017659

**Closed as completed by dirk-thomas** 2020-06-12 17:39 UTC
Labels: bug
