### ISSUE TITLE
c++ Plugins nodehandle is not in global namespace

### ISSUE THREAD

**Issue by Squelsh** [ros-visualization/rqt#99] opened 2015-01-02 01:44 UTC
As stated also by others (http://answers.ros.org/question/109371/remapping-rqt-published-topics/) the topics/services within a C++ rqt-Plugin seem to be in a private namespace, named by the plugin name.

This is not the case with python plugins, where non-global topics are correctly pushed down into the namespace that is given via "ROS_NAMESPACE", when rqt is started.

Even if this is by intention, it should be consistent between C++ and Python.

**Comment by dirk-thomas** [comment] 2015-04-30 00:34
A rqt C++ plugin is not a ROS node but a ROS nodelet. Simply because roscpp does not support to run more then a single node per process. A nodelet always runs in a namespace (http://wiki.ros.org/nodelet) but can still be remapped.

Since this described behavior is intended and by design I will close this ticket since it can't be changed.

**Closed as completed by dirk-thomas** 2015-04-30 00:34 UTC
Labels: wontfix
