### ISSUE TITLE
rqt_plot Aborted in Ubuntu18.04

### ISSUE THREAD

**Issue by JessieTang2018** [ros-visualization/rqt#222] opened 2020-03-26 02:44 UTC
I was following the tutorial:http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics
But when I run:
  rosrun rqt_plot rqt_plot
I got errors :
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 77, in paintEvent
    self.resizeEvent(event)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_plot/data_plot/mat_data_plot.py", line 110, in resizeEvent
    self.figure.tight_layout()
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 2031, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1881, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 241, in update
    raise ValueError('bottom cannot be >= top')
ValueError: bottom cannot be >= top
Aborted (core dumped)

Can anyone help?

**Comment by dirk-thomas** [comment] 2020-03-26 05:45
Duplicate of ros-visualization/rqt_plot#50.

**Closed as completed by dirk-thomas** 2020-03-26 05:45 UTC
Labels: duplicate
