### ISSUE TITLE
rqt crashes when a C++ plugin throws an exception

### ISSUE THREAD

**Issue by acpl00** [ros-visualization/rqt#97] opened 2014-05-14 10:30 UTC
Dear All,

I launch rqt and then I insert the rviz plugin. However, whenever I try to open a static map topic within rviz, rqt crashes with  the following error:

 Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range
Aborted (core dumped)

I have experience this issue in different computers.

Thus, when I  run rviz as a stand alone application with the command rosrun rviz rviz and then I launch a static map topic, it works quite fine

I am running Hydro on Ubuntu 12.04

In advance thank you for your help.

**Comment by DorianScholz** [comment] 2014-05-14 13:45
@dirk-thomas: I'm not sure whether this should be solved in the rqt_rviz plugin or in the rqt_cpp wrapper.
Should there be a default QApplication::notify() handler in rqt to prevent the any cpp plugin from crashing the whole rqt?

@acpl00: Besides the problem of rqt crashing on such exceptions, I guess there is also a problem with your time field in the map topic:

```
what(): Time is out of dual 32-bit range
```

Can you confirm this exception is also produced when subscribing from standard standalone rviz?
Even if rviz is not crashing it should produce this exception somewhere in the logs, maybe in debug/verbose mode?

**Comment by dirk-thomas** [comment] 2014-07-03 17:17
The exception can't be catched in a `notify` function of a custom Python `QApplication`. And I don't see a way to reimplement the C++ part of `QApplication::notify()` from Python since `qt_gui_core` is Python-only. If someone has an idea how to achieve that I would be happy to integrate it.

Btw I updated the issue title to describe the problem better.

**Comment by dkargin** [comment] 2015-02-03 15:22
I confirm that standalone RViz also has the same problem.

**Comment by dirk-thomas** [comment] 2015-02-03 17:30
@FrostHand can you please describe the scenario in detail in order to reproduce your problem.

The original ticket explicitly mentions that it does not happen for standalone rviz.

**Comment by dkargin** [comment] 2015-02-04 14:32
I can send rviz config and ros bag files to you. I guess there are invalid messages stored in this file.

**Comment by dirk-thomas** [comment] 2015-02-04 16:32
If there problem happens in standalone rviz please fill a new ticket with all the information in the rviz repository.

**Comment by dirk-thomas** [comment] 2015-04-30 00:19
Since I can't imagine to catch these from Python I will mark it as "wontfix" and close it. If someone has a good idea how to achieve that please comment and it can be reopened.

**Closed as completed** 2015-04-30 00:19 UTC
Labels: wontfix
